### PR TITLE
Use the original lib repo, not copied sources

### PR DESCRIPTION
**Pull request by QRPp**
Use Mongoose OS module feature to separately source and build the original
milesburton's DallasTemperature Arduino library instead of the outdated bundled
fork.

(Probably also neatly keeps licencing separate: the original is LGPL 2, the wrapper is Apache 2.)

(**NB!**  Won't build until https://github.com/mongoose-os-libs/arduino-compat/pull/7 is merged!)

(Question: is it beneficial to pin the module to a the current known-to-work version or commit?)

### CODE REVIEW

**Comment by rojer** [comment]
Question: is it beneficial to pin the module to a the current known-to-work version or commit?

yeah, i think so. let's pin to current master.

**Comment by QRPp** [comment]
OK, I've set **`version:`** of the module to the latest upstream master commit.  Will that do?

**Comment by rojer** [comment]
LG

**Comment by rojer** [comment]
thanks!

**Pull request merged**
